global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'kmfacil-backend'
    metrics_path: '/actuator/prometheus'

    scrape_interval: 15s

    static_configs:
      - targets: [ 'host.docker.internal:8080' ]