spring:
  application:
    name: kmfacil

  config:
    import: file:.env.properties

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_LOCAL_URL}:${POSTGRES_LOCAL_PORT}/${POSTGRES_DB}
    #    url: jdbc:postgresql://${POSTGRES_DOCKER_URL}:${POSTGRES_DOCKER_PORT}/${POSTGRES_DB}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariCP
      initialization-fail-timeout: 0
      leak-detection-threshold: 2000

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
