{
 "title": "Km Fácil Dashboard",
 "description": "Dashboard for Km Fácil backend Metrics",
 "time": { "from": "now-5h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"},id)"
   },
   {
    "name": "executor_pool",
    "label": "Executor Pool",
    "query": {
     "query": "label_values(executor_pool_max_threads{application=\"$application\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{application=\"$application\", instance=~\"$instance\"})*1000"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Ready Time",
   "type": "stat",
   "description": "Time taken for the application to be ready to service requests",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "application_ready_time_seconds{application=\"$application\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{application=\"$application\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Time taken to start the application",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_started_time_seconds{application=\"$application\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "timeseries",
   "description": "Tracks the number of file descriptors currently open by the JVM process.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max{application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "description": "Tracks the total and usable space for path.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "disk_total_bytes{application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Total Space Bytes"
    },
    {
     "expr": "disk_free_bytes{application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Usable Space Bytes"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Represents the recent CPU usage by the JVM (Java Virtual Machine) process.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "- Represents the average system load over the last 1 minute.\n- Indicates the sum of:\n  - Executable entities waiting for CPU availability (processes queued for execution).\n  - Entities running on available processors.\n\n- The value reflects the competition between processes for the use of CPU and other resources.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1881 },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", application=\"$application\", area=\"heap\"})",
       "legendFormat": "Heap Used Bytes"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", application=\"$application\", area=\"nonheap\"})",
       "legendFormat": "Non-Heap Used Bytes"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1881 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\", application=\"$application\"})",
       "legendFormat": "Max Bytes"
      }
     ]
    },
    {
     "title": "Max Commited Memory",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1881 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=~\"$instance\", application=\"$application\"})",
       "legendFormat": "Max Bytes"
      }
     ]
    },
    {
     "title": "$memory_pool_heap (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1889 },
     "repeat": "memory_pool_heap",
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1897 },
     "repeat": "memory_pool_nonheap",
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1905 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1905 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_classes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "description": "Measures the estimated memory currently in use by buffers in the direct pool (buffers allocated outside of the Java heap for efficient I/O operations).",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1913 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=~\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "description": "Measures the estimated memory currently in use by buffers in the mapped pool (buffers that map to files in memory).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1913 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=~\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1920 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Promoted"
      }
     ]
    },
    {
     "title": "Young Generation Allocated Memory Between GC",
     "type": "timeseries",
     "description": "- Counts the total bytes allocated in the Young Generation between GC events.\n- Increments whenever the Young Generation heap increases in size between garbage collections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1920 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_gc_memory_allocated_bytes_total{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Allocated"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daemon Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 834 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Live Threads",
     "type": "timeseries",
     "description": "The current number of live threads including both daemon and non-daemon threads",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 834 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Live Threads"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Peak Threads"
      }
     ]
    },
    {
     "title": "Threads States",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1222 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Threads in $executor_pool [pool]",
     "type": "timeseries",
     "description": "The current number of threads in the pool.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1230 },
     "repeat": "executor_pool",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "executor_pool_size_threads{instance=~\"$instance\", application=\"$application\", name=~\"$executor_pool\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "executor_pool_core_threads{instance=~\"$instance\", application=\"$application\", name=~\"$executor_pool\"}",
       "legendFormat": "Core"
      },
      {
       "expr": "executor_pool_max_threads{instance=~\"$instance\", application=\"$application\", name=~\"$executor_pool\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Tasks in $executor_pool [pool]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1239 },
     "repeat": "executor_pool",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "executor_completed_tasks_total{instance=~\"$instance\", application=\"$application\", name=~\"$executor_pool\"}",
       "legendFormat": "Completed"
      },
      {
       "expr": "executor_queued_tasks{instance=~\"$instance\", application=\"$application\", name=~\"$executor_pool\"}",
       "legendFormat": "Queued"
      },
      {
       "expr": "executor_queue_remaining_tasks{instance=~\"$instance\", application=\"$application\", name=~\"$executor_pool\"}",
       "legendFormat": "Remaining"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 835 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{instance=~\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 835 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC CPU Overhead",
     "type": "timeseries",
     "description": "CPU usage by GC activities.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 844 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "jvm_gc_overhead{instance=~\"$instance\", application=\"$application\"} * 100",
       "legendFormat": "CPU Overhead"
      }
     ]
    },
    {
     "title": "Promoted Bytes in Old Generation After GC",
     "type": "timeseries",
     "description": "- Measures the sum of positive promotions in the size of the Old Generation after a garbage collection (GC).\n- Promotions occur when objects survive garbage collection in the Young Generation and are moved to the Old Generation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 844 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_gc_memory_promoted_bytes_total{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Promoted Bytes"
      }
     ]
    },
    {
     "title": "Old Generation Memory Usage After GC",
     "type": "timeseries",
     "description": "Measures the percentage of memory occupied in the Old Generation after the last garbage collection (GC).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 852 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "jvm_memory_usage_after_gc_percent{instance=~\"$instance\", application=\"$application\"} * 100",
       "legendFormat": "Memory Usage"
      }
     ]
    },
    {
     "title": "Old Generation Size After GC",
     "type": "timeseries",
     "description": "Represents the current size of the Old Generation after the last garbage collection (GC). That is, the amount of memory occupied by surviving objects after cleanup.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 852 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_gc_live_data_size_bytes{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Old Generation Size"
      }
     ]
    }
   ]
  },
  {
   "title": "HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Min Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4633 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_min{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4633 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4633 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4814 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_max{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4814 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
      }
     ]
    },
    {
     "title": "Connection Creation Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4818 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hikaricp_connections_creation_seconds_sum{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Creation Time"
      }
     ]
    },
    {
     "title": "Connection Usage Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4818 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_sum{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Usage Time"
      }
     ]
    },
    {
     "title": "Connection Acquire Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4818 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hikaricp_connections_acquire_seconds_sum{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Acquire Time"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1984 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Total Request Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1991 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1998 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Data Repository Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Invocation Max Seconds",
     "type": "timeseries",
     "description": "The maximum time (in seconds) spent on a single invocation of a specific repository method.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1632 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "spring_data_repository_invocations_seconds_max{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{repository}}.{{method}}"
      }
     ]
    },
    {
     "title": "Invokation Total Seconds",
     "type": "timeseries",
     "description": "The total accumulated time (in seconds) spent across all invocations of the method.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1640 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "spring_data_repository_invocations_seconds_sum{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{repository}}.{{method}}"
      }
     ]
    },
    {
     "title": "Invocation Count",
     "type": "timeseries",
     "description": "The total number of invocations of the registered repository method.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1648 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "spring_data_repository_invocations_seconds_count{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{repository}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Error Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1633 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_global_error_total{instance=~\"$instance\", application=\"$application\"}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1633 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_connections_config_max_connections{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Hits",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1633 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_cache_hit_total{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "HIts"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1633 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tomcat_sessions_active_current_sessions{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Active Sessions"
      }
     ]
    },
    {
     "title": "Servlet Error Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1637 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_servlet_error_total{instance=~\"$instance\", application=\"$application\"}"
      }
     ]
    },
    {
     "title": "Thread Config Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1637 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_threads_config_max_threads{instance=~\"$instance\", application=\"$application\"}"
      }
     ]
    },
    {
     "title": "Cache Access",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1637 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_cache_access_total{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Access Total"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1641 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_threads_current_threads{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Current Thread"
      },
      {
       "expr": "tomcat_threads_busy_threads{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Current Thread Busy"
      }
     ]
    },
    {
     "title": "Active Sessions Lifetime",
     "type": "timeseries",
     "description": "Measures the maximum lifetime of sessions that remain active in Tomcat.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1641 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tomcat_sessions_alive_max_seconds{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Active Sessions Lifetime"
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1649 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tomcat_connections_current_connections{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Global Sent & Received Bytes [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1649 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(tomcat_global_sent_bytes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Sent Bytes"
      },
      {
       "expr": "irate(tomcat_global_received_bytes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Received Bytes"
      }
     ]
    },
    {
     "title": "Global Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1657 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "tomcat_global_request_seconds_count{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Global Requests Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1657 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tomcat_global_request_seconds_sum{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Servlet Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1665 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tomcat_servlet_request_seconds_count{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Servlet Requests Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1665 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tomcat_servlet_request_seconds_sum{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Listener Max Seconds",
     "type": "timeseries",
     "description": "The maximum time (in seconds) spent by a Kafka Listener to process a message.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1738 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "spring_kafka_listener_seconds_max{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Listener Total Seconds",
     "type": "timeseries",
     "description": "The total accumulated time (in seconds) spent by the Kafka Listener processing messages.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1746 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "spring_kafka_listener_seconds_sum{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Listener Total Messages",
     "type": "timeseries",
     "description": "The total number of messages processed by the Kafka Listener.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1754 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "spring_kafka_listener_seconds_count{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Info Logs [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3000 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"info\"}[5m])",
       "legendFormat": "Info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Error Logs [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3000 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"error\"}[5m])",
       "legendFormat": "Error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Warn Logs [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3007 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
       "legendFormat": "Warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Debug Logs [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3007 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
       "legendFormat": "Debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Trace Logs [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3007 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
       "legendFormat": "Trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}